const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Plugins.Mouse,
		C3.Behaviors.Tween,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.ToggleBoolVar,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Behaviors.DragnDrop.Cnds.IsDragging,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare
	];
};
self.C3_JsPropNameTable = [
	{Audio: 0},
	{Touch: 0},
	{Browser: 0},
	{randomPos: 0},
	{singlePlayer: 0},
	{layoutName: 0},
	{a: 0},
	{b: 0},
	{c: 0},
	{d: 0},
	{Mouse: 0},
	{dependItemUID: 0},
	{value: 0},
	{isComplete: 0},
	{hasDepend: 0},
	{cambalonalt1: 0},
	{erlenmayer1: 0},
	{ücayak1: 0},
	{amyanttel1: 0},
	{termometre1: 0},
	{balontıpa1: 0},
	{kıskac1: 0},
	{tıpa1: 0},
	{ücayakönparca1: 0},
	{posX: 0},
	{posY: 0},
	{Tween: 0},
	{menuBg1: 0},
	{sogutucuBtn1: 0},
	{termometreBtn1: 0},
	{sporDestekBtn1: 0},
	{kiskacBtn1: 0},
	{bunzenBekiBtn1: 0},
	{erlenmayerBtn1: 0},
	{tipaBtn1: 0},
	{camBalonBtn1: 0},
	{amyantTelBtn1: 0},
	{ucAyakBtn1: 0},
	{menuBtn: 0},
	{fullScreenBtn: 0},
	{shareBtn: 0},
	{audioBtn: 0},
	{refreshBtn: 0},
	{infoBg: 0},
	{closeBtn: 0},
	{spordestek1: 0},
	{bünzenbeki1: 0},
	{sogutucu1: 0},
	{info: 0},
	{masa: 0},
	{Genel: 0},
	{balonjoje3: 0},
	{ucAyak2: 0},
	{amyanTel2: 0},
	{altHuni2: 0},
	{cambalon2: 0},
	{ispirtoOcagi2: 0},
	{puar2: 0},
	{pipet2: 0},
	{altBeher2: 0},
	{ustHuni2: 0},
	{kagitSuzgec2: 0},
	{kiskac2: 0},
	{kiskacBtn2: 0},
	{beherBtn3: 0},
	{pipetBtn2: 0},
	{ispirtoBtn2: 0},
	{huniBtn2: 0},
	{balonJojeBtn2: 0},
	{puarBtn2: 0},
	{sporDestekBtn2: 0},
	{suzgecKagidiBtn2: 0},
	{camBalonBtn2: 0},
	{amyantTelBtn2: 0},
	{ucAyakBtn2: 0},
	{spordestek2: 0},
	{ustBeher2: 0},
	{menuBg2: 0},
	{büret3: 0},
	{camBoru3: 0},
	{dereceliSilindir3: 0},
	{havan3: 0},
	{menuBg3: 0},
	{spatül3: 0},
	{maşa3: 0},
	{kroze3: 0},
	{kiskac3: 0},
	{sporDestekBtn3: 0},
	{masaBtn3: 0},
	{dereceliSilindirBtn3: 0},
	{kıskacBtn3: 0},
	{camBoruBtn3: 0},
	{spatülBtn3: 0},
	{havanBtn3: 0},
	{büretBtn3: 0},
	{krozeBtn3: 0},
	{erlenmayerBtn3: 0},
	{erlenmayer3: 0},
	{spordestek: 0},
	{ayirmaHunisi4: 0},
	{piset4: 0},
	{menuBg4: 0},
	{kiskac4: 0},
	{pisetBtn4: 0},
	{sporDestekBtn4: 0},
	{damlalıkBtn4: 0},
	{ayirmaHunisiBtn4: 0},
	{bagetBtn4: 0},
	{deneyTüpüBtn4: 0},
	{beherBtn4: 0},
	{saatCamiBtn4: 0},
	{kiskacBtn4: 0},
	{altBeher4: 0},
	{baget4: 0},
	{ustBeher4: 0},
	{saatCami4: 0},
	{damlalık4: 0},
	{sporDestek4: 0},
	{deneyTüpü4: 0},
	{homeBtn: 0},
	{cambalonUst1: 0},
	{Sprite2: 0},
	{loaderEmpty: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{deneyBtn: 0},
	{deneyItems1: 0},
	{DragDrop: 0},
	{menuItems1: 0},
	{deneyItems2: 0},
	{menuItems2: 0},
	{deneyItems3: 0},
	{menuItems3: 0},
	{deneyItems4: 0},
	{menuItems4: 0},
	{soundControl: 0},
	{animationQueue: 0},
	{animStart: 0},
	{selectDeneyItemMode: 0},
	{completeCount: 0},
	{UID: 0},
	{animationQueue2: 0},
	{animStart2: 0},
	{selectDeneyItemMode2: 0},
	{completeCount2: 0},
	{animationQueue3: 0},
	{animStart3: 0},
	{selectDeneyItemMode3: 0},
	{completeCount3: 0},
	{animationQueue4: 0},
	{animStart4: 0},
	{selectDeneyItemMode4: 0},
	{completeCount4: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	randomPos: class extends self.IArrayInstance {},
	singlePlayer: class extends self.ISpriteInstance {},
	a: class extends self.ISpriteInstance {},
	b: class extends self.ISpriteInstance {},
	c: class extends self.ISpriteInstance {},
	d: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	cambalonalt1: class extends self.ISpriteInstance {},
	erlenmayer1: class extends self.ISpriteInstance {},
	ücayak1: class extends self.ISpriteInstance {},
	amyanttel1: class extends self.ISpriteInstance {},
	termometre1: class extends self.ISpriteInstance {},
	balontıpa1: class extends self.ISpriteInstance {},
	kıskac1: class extends self.ISpriteInstance {},
	tıpa1: class extends self.ISpriteInstance {},
	ücayakönparca1: class extends self.ISpriteInstance {},
	menuBg1: class extends self.ISpriteInstance {},
	sogutucuBtn1: class extends self.ISpriteInstance {},
	termometreBtn1: class extends self.ISpriteInstance {},
	sporDestekBtn1: class extends self.ISpriteInstance {},
	kiskacBtn1: class extends self.ISpriteInstance {},
	bunzenBekiBtn1: class extends self.ISpriteInstance {},
	erlenmayerBtn1: class extends self.ISpriteInstance {},
	tipaBtn1: class extends self.ISpriteInstance {},
	camBalonBtn1: class extends self.ISpriteInstance {},
	amyantTelBtn1: class extends self.ISpriteInstance {},
	ucAyakBtn1: class extends self.ISpriteInstance {},
	menuBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	infoBg: class extends self.ISpriteInstance {},
	closeBtn: class extends self.ISpriteInstance {},
	spordestek1: class extends self.ISpriteInstance {},
	bünzenbeki1: class extends self.ISpriteInstance {},
	sogutucu1: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	masa: class extends self.ISpriteInstance {},
	Genel: class extends self.ISpriteInstance {},
	balonjoje3: class extends self.ISpriteInstance {},
	ucAyak2: class extends self.ISpriteInstance {},
	amyanTel2: class extends self.ISpriteInstance {},
	altHuni2: class extends self.ISpriteInstance {},
	cambalon2: class extends self.ISpriteInstance {},
	ispirtoOcagi2: class extends self.ISpriteInstance {},
	puar2: class extends self.ISpriteInstance {},
	pipet2: class extends self.ISpriteInstance {},
	altBeher2: class extends self.ISpriteInstance {},
	ustHuni2: class extends self.ISpriteInstance {},
	kagitSuzgec2: class extends self.ISpriteInstance {},
	kiskac2: class extends self.ISpriteInstance {},
	kiskacBtn2: class extends self.ISpriteInstance {},
	beherBtn3: class extends self.ISpriteInstance {},
	pipetBtn2: class extends self.ISpriteInstance {},
	ispirtoBtn2: class extends self.ISpriteInstance {},
	huniBtn2: class extends self.ISpriteInstance {},
	balonJojeBtn2: class extends self.ISpriteInstance {},
	puarBtn2: class extends self.ISpriteInstance {},
	sporDestekBtn2: class extends self.ISpriteInstance {},
	suzgecKagidiBtn2: class extends self.ISpriteInstance {},
	camBalonBtn2: class extends self.ISpriteInstance {},
	amyantTelBtn2: class extends self.ISpriteInstance {},
	ucAyakBtn2: class extends self.ISpriteInstance {},
	spordestek2: class extends self.ISpriteInstance {},
	ustBeher2: class extends self.ISpriteInstance {},
	menuBg2: class extends self.ISpriteInstance {},
	büret3: class extends self.ISpriteInstance {},
	camBoru3: class extends self.ISpriteInstance {},
	dereceliSilindir3: class extends self.ISpriteInstance {},
	havan3: class extends self.ISpriteInstance {},
	menuBg3: class extends self.ISpriteInstance {},
	spatül3: class extends self.ISpriteInstance {},
	maşa3: class extends self.ISpriteInstance {},
	kroze3: class extends self.ISpriteInstance {},
	kiskac3: class extends self.ISpriteInstance {},
	sporDestekBtn3: class extends self.ISpriteInstance {},
	masaBtn3: class extends self.ISpriteInstance {},
	dereceliSilindirBtn3: class extends self.ISpriteInstance {},
	kıskacBtn3: class extends self.ISpriteInstance {},
	camBoruBtn3: class extends self.ISpriteInstance {},
	spatülBtn3: class extends self.ISpriteInstance {},
	havanBtn3: class extends self.ISpriteInstance {},
	büretBtn3: class extends self.ISpriteInstance {},
	krozeBtn3: class extends self.ISpriteInstance {},
	erlenmayerBtn3: class extends self.ISpriteInstance {},
	erlenmayer3: class extends self.ISpriteInstance {},
	spordestek: class extends self.ISpriteInstance {},
	ayirmaHunisi4: class extends self.ISpriteInstance {},
	piset4: class extends self.ISpriteInstance {},
	menuBg4: class extends self.ISpriteInstance {},
	kiskac4: class extends self.ISpriteInstance {},
	pisetBtn4: class extends self.ISpriteInstance {},
	sporDestekBtn4: class extends self.ISpriteInstance {},
	damlalıkBtn4: class extends self.ISpriteInstance {},
	ayirmaHunisiBtn4: class extends self.ISpriteInstance {},
	bagetBtn4: class extends self.ISpriteInstance {},
	deneyTüpüBtn4: class extends self.ISpriteInstance {},
	beherBtn4: class extends self.ISpriteInstance {},
	saatCamiBtn4: class extends self.ISpriteInstance {},
	kiskacBtn4: class extends self.ISpriteInstance {},
	altBeher4: class extends self.ISpriteInstance {},
	baget4: class extends self.ISpriteInstance {},
	ustBeher4: class extends self.ISpriteInstance {},
	saatCami4: class extends self.ISpriteInstance {},
	damlalık4: class extends self.ISpriteInstance {},
	sporDestek4: class extends self.ISpriteInstance {},
	deneyTüpü4: class extends self.ISpriteInstance {},
	homeBtn: class extends self.ISpriteInstance {},
	cambalonUst1: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	deneyBtn: class extends self.ISpriteInstance {},
	deneyItems1: class extends self.ISpriteInstance {},
	menuItems1: class extends self.ISpriteInstance {},
	deneyItems2: class extends self.ISpriteInstance {},
	menuItems2: class extends self.ISpriteInstance {},
	deneyItems3: class extends self.ISpriteInstance {},
	menuItems3: class extends self.ISpriteInstance {},
	deneyItems4: class extends self.ISpriteInstance {},
	menuItems4: class extends self.ISpriteInstance {}
}